-- Migration 1: CreateTenantTable
CREATE TABLE "Tenants" (
    "Id" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Slug" character varying(100) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Tenants" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Tenants_Slug" ON "Tenants" ("Slug");

-- Migration 2: AddIdentity
CREATE TABLE "Users" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Role" integer NOT NULL,
    "GoogleId" character varying(256),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Users_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "Roles" (
    "Id" uuid NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_Roles" PRIMARY KEY ("Id")
);
CREATE TABLE "UserRoles" (
    "UserId" uuid NOT NULL,
    "RoleId" uuid NOT NULL,
    CONSTRAINT "PK_UserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_UserRoles_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserRoles_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE TABLE "UserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_UserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserClaims_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE TABLE "UserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" uuid NOT NULL,
    CONSTRAINT "PK_UserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_UserLogins_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE TABLE "RoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" uuid NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_RoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RoleClaims_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
);
CREATE TABLE "UserTokens" (
    "UserId" uuid NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_UserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_UserTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE TABLE "RefreshTokens" (
    "Id" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "Token" character varying(128) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "RevokedAt" timestamp with time zone,
    CONSTRAINT "PK_RefreshTokens" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RefreshTokens_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_Users_TenantId_Email" ON "Users" ("TenantId", "Email");
CREATE UNIQUE INDEX "IX_Users_GoogleId" ON "Users" ("GoogleId") WHERE "GoogleId" IS NOT NULL;
CREATE INDEX "IX_Users_NormalizedEmail" ON "Users" ("NormalizedEmail");
CREATE INDEX "IX_Users_NormalizedUserName" ON "Users" ("NormalizedUserName");
CREATE INDEX "IX_Users_TenantId" ON "Users" ("TenantId");
CREATE UNIQUE INDEX "IX_Roles_NormalizedName" ON "Roles" ("NormalizedName");
CREATE INDEX "IX_UserRoles_RoleId" ON "UserRoles" ("RoleId");
CREATE INDEX "IX_UserClaims_UserId" ON "UserClaims" ("UserId");
CREATE INDEX "IX_UserLogins_UserId" ON "UserLogins" ("UserId");
CREATE INDEX "IX_RoleClaims_RoleId" ON "RoleClaims" ("RoleId");
CREATE INDEX "IX_RefreshTokens_UserId" ON "RefreshTokens" ("UserId");

-- Migration 3: AddStudents
CREATE TABLE "Students" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Nome" character varying(200) NOT NULL,
    "DataNascimento" timestamp with time zone NOT NULL,
    "Cpf" character varying(14),
    "Turma" character varying(50) NOT NULL,
    "AnoLetivo" integer NOT NULL,
    "Status" integer NOT NULL,
    "Observacoes" character varying(1000),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Students" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Students_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "StudentParents" (
    "StudentId" uuid NOT NULL,
    "ParentId" uuid NOT NULL,
    CONSTRAINT "PK_StudentParents" PRIMARY KEY ("StudentId", "ParentId"),
    CONSTRAINT "FK_StudentParents_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_StudentParents_Users_ParentId" FOREIGN KEY ("ParentId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Students_TenantId" ON "Students" ("TenantId");
CREATE INDEX "IX_Students_TenantId_Nome" ON "Students" ("TenantId", "Nome");
CREATE UNIQUE INDEX "IX_Students_TenantId_Cpf" ON "Students" ("TenantId", "Cpf") WHERE "Cpf" IS NOT NULL;
CREATE INDEX "IX_StudentParents_ParentId" ON "StudentParents" ("ParentId");

-- Migration 4: AddEnrollments
CREATE TABLE "EnrollmentPeriods" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Nome" character varying(200) NOT NULL,
    "DataInicio" timestamp with time zone NOT NULL,
    "DataFim" timestamp with time zone NOT NULL,
    "AnoLetivo" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_EnrollmentPeriods" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EnrollmentPeriods_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "Enrollments" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "EnrollmentPeriodId" uuid NOT NULL,
    "Status" integer NOT NULL,
    "MotivoRejeicao" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "ApprovedAt" timestamp with time zone,
    CONSTRAINT "PK_Enrollments" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Enrollments_EnrollmentPeriods_EnrollmentPeriodId" FOREIGN KEY ("EnrollmentPeriodId") REFERENCES "EnrollmentPeriods" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Enrollments_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Enrollments_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_EnrollmentPeriods_TenantId" ON "EnrollmentPeriods" ("TenantId");
CREATE INDEX "IX_EnrollmentPeriods_TenantId_AnoLetivo" ON "EnrollmentPeriods" ("TenantId", "AnoLetivo");
CREATE INDEX "IX_Enrollments_TenantId" ON "Enrollments" ("TenantId");
CREATE INDEX "IX_Enrollments_StudentId" ON "Enrollments" ("StudentId");
CREATE INDEX "IX_Enrollments_TenantId_Status" ON "Enrollments" ("TenantId", "Status");
CREATE INDEX "IX_Enrollments_EnrollmentPeriodId" ON "Enrollments" ("EnrollmentPeriodId");

-- Migration 5: AddDocuments
CREATE TABLE "DocumentTypes" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Nome" character varying(200) NOT NULL,
    "Descricao" text,
    "IsRequired" boolean NOT NULL DEFAULT TRUE,
    "ValidadeMeses" integer NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_DocumentTypes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DocumentTypes_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "Documents" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "StudentId" uuid NOT NULL,
    "DocumentTypeId" uuid NOT NULL,
    "NomeArquivo" character varying(500) NOT NULL,
    "CaminhoArquivo" character varying(1000) NOT NULL,
    "Status" integer NOT NULL,
    "DataValidade" timestamp with time zone,
    "MotivoRejeicao" character varying(500),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    "VerifiedAt" timestamp with time zone,
    CONSTRAINT "PK_Documents" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Documents_DocumentTypes_DocumentTypeId" FOREIGN KEY ("DocumentTypeId") REFERENCES "DocumentTypes" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Documents_Students_StudentId" FOREIGN KEY ("StudentId") REFERENCES "Students" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Documents_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_DocumentTypes_TenantId" ON "DocumentTypes" ("TenantId");
CREATE INDEX "IX_Documents_TenantId" ON "Documents" ("TenantId");
CREATE INDEX "IX_Documents_StudentId" ON "Documents" ("StudentId");
CREATE INDEX "IX_Documents_TenantId_Status" ON "Documents" ("TenantId", "Status");
CREATE INDEX "IX_Documents_DocumentTypeId" ON "Documents" ("DocumentTypeId");

-- Migration 6: AddNotifications
CREATE TABLE "Notifications" (
    "Id" uuid NOT NULL,
    "TenantId" uuid NOT NULL,
    "Titulo" character varying(200) NOT NULL,
    "Mensagem" character varying(2000) NOT NULL,
    "Tipo" integer NOT NULL,
    "ReferenceId" uuid,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Notifications_Tenants_TenantId" FOREIGN KEY ("TenantId") REFERENCES "Tenants" ("Id") ON DELETE RESTRICT
);
CREATE TABLE "UserNotifications" (
    "Id" uuid NOT NULL,
    "NotificationId" uuid NOT NULL,
    "UserId" uuid NOT NULL,
    "IsRead" boolean NOT NULL,
    "ReadAt" timestamp with time zone,
    CONSTRAINT "PK_UserNotifications" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserNotifications_Notifications_NotificationId" FOREIGN KEY ("NotificationId") REFERENCES "Notifications" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserNotifications_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);
CREATE INDEX "IX_Notifications_TenantId" ON "Notifications" ("TenantId");
CREATE INDEX "IX_UserNotifications_UserId_IsRead" ON "UserNotifications" ("UserId", "IsRead");
CREATE INDEX "IX_UserNotifications_NotificationId" ON "UserNotifications" ("NotificationId");

-- Register migrations in history
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES 
  ('20260808190000_CreateTenantTable', '10.0.0'),
  ('20260808191000_AddIdentity', '10.0.0'),
  ('20260808195000_AddStudents', '10.0.0'),
  ('20260808200000_AddEnrollments', '10.0.0'),
  ('20260808203000_AddDocuments', '10.0.0'),
  ('20260808210000_AddNotifications', '10.0.0');
